apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mizdooni-mysql
  name: mizdooni-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mizdooni-mysql
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mizdooni-mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: Mizdooni
            - name: MYSQL_ROOT_PASSWORD
              value: Aa123456@@
          image: mysql:latest
          livenessProbe:
            exec:
              command:
                - mysqladmin ping -h localhost
            failureThreshold: 5
            periodSeconds: 10
          name: mizdooni-mysql
          ports:
            - containerPort: 3306
              protocol: TCP
      restartPolicy: Always
