apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mizdooni-mysql
  name: mizdooni-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mizdooni-mysql
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mizdooni-mysql
    spec:
      containers:
        - name: mizdooni-mysql
          image: mysql:latest
          env:
            - name: MYSQL_DATABASE
              value: Mizdooni
            - name: MYSQL_ROOT_PASSWORD
              value: Aa123456@@
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              memory: "200Mi"  # Request 200 MiB of memory
              cpu: "100m"      # Request 100 millicpu (0.1 CPU cores)
            limits:
              memory: "500Mi"  # Limit to 500 MiB of memory
              cpu: "0.5"       # Limit to 0.5 CPU cores (500 millicpu)
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      restartPolicy: Always
