apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mizdooni-app
  name: mizdooni-app
spec:
  replicas: 2  # Updated number of replicas
  selector:
    matchLabels:
      io.kompose.service: mizdooni-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mizdooni-app
    spec:
      affinity:  # Adding affinity rules
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "io.kompose.service"
                    operator: In
                    values:
                      - mizdooni-app
              topologyKey: "kubernetes.io/hostname"
      containers:
        - env:
            - name: ELASTIC_APM_SERVER_URLS
              value: http://apm-server:8200
            - name: SPRING_DATASOURCE_PASSWORD
              value: Aa123456@@
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mizdooni-mysql:3306/Mizdooni
            - name: SPRING_DATASOURCE_USERNAME
              value: root
          resources:
            requests:
              memory: "200Mi"  # Request 200 MiB of memory
              cpu: "500m"      # Request 100 millicpu (0.1 CPU cores)
            limits:
              memory: "500Mi"  # Limit to 500 MiB of memory
              cpu: "0.5"       # Limit to 0.5 CPU cores (500 millicpu)
          image: pooriatajmehrabi/mizdooni_backend:1.0.0
          name: mizdooni-app
          ports:
            - containerPort: 8090
              protocol: TCP
      restartPolicy: Always
