apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: react-app
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: react-app
    spec:
      containers:
        - env:
            - name: REACT_APP_BACKEND_URL
              value: https://mizdooni-back:8090
          image: pooriatajmehrabi/mizdooni_frontend:latest
          name: react-app
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
