version: "2.2"
name: mizdooni_app
services:
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.21
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
      - 8200:8200
    networks:
      - elastic
      - mizdooni_network
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
      - mizdooni_network
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.21
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic
      - mizdooni_network
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

  mizdooni-mysql:
    image: mysql:latest
    container_name: mizdooni-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Aa123456@@
      - MYSQL_DATABASE=Mizdooni
    ports:
      - 3307:3306
    networks:
      - mizdooni_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5

  react-app:
    image: pooriatajmehrabi/mizdooni_frontend:latest
    depends_on:
      - mizdooni-app
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: https://127.0.0.1:8090
    ports:
      - 80:80
      - 443:443
      - 3001:3000
    networks:
      - mizdooni_network
    environment:
      - REACT_APP_BACKEND_URL=https://mizdooni-back:8090

  mizdooni-app:
    image: pooriatajmehrabi/mizdooni_backend:latest
    ports:
      - 8090:8090
    depends_on:
      apm-server:
        condition: service_healthy
      mizdooni-mysql:
        condition: service_healthy
    build:
      context: ./back/Mizdooni
      dockerfile: Dockerfile
    networks:
      - mizdooni_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mizdooni-mysql:3306/Mizdooni
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Aa123456@@
      - ELASTIC_APM_SERVER_URLS=http://apm-server:8200

volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge
  mizdooni_network:
    driver: bridge
